[package]
name = "monkey_interpreter"
version = "1.0.0"
authors = ["Wessel van Lit <wessel@litdev.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
